"""Replay tests — verify that saved event histories replay cleanly against
any new workflow code.

Workflows in this POC can stay open for up to 67 days.  Any non-additive code
change (inserting a new activity call, reordering branches, changing a signal
name) will throw NonDeterminismException on every open execution during the
next deploy.  These tests catch that *before* it reaches production.

Fixtures (JSON files in tests/fixtures/) are generated by running real
workflows against a local Temporal server and exporting their histories.
Regenerate them after any non-additive workflow change, then commit the
updated JSON.

Usage:
    # Generate / refresh fixtures
    python tests/fixtures/generate_replay_fixtures.py

    # Run replay tests
    pytest tests/test_replay.py
"""

from __future__ import annotations

import pathlib

import pytest
from temporalio.client import WorkflowHistory
from temporalio.worker import Replayer

from oms.workflows import OrderProcessingWorkflow

_FIXTURES = pathlib.Path(__file__).parent / "fixtures"


def _load_history(name: str) -> WorkflowHistory:
    path = _FIXTURES / f"{name}.json"
    if not path.exists():
        pytest.skip(
            f"Replay fixture not found: {path}\n"
            "Generate it by running: python tests/fixtures/generate_replay_fixtures.py"
        )
    return WorkflowHistory.from_json(name, path.read_text())


@pytest.mark.asyncio
async def test_replay_happy_path() -> None:
    """Full happy path: validation → risk → payment → PIM → Kafka → FULFILLED."""
    replayer = Replayer(workflows=[OrderProcessingWorkflow])
    await replayer.replay_workflow(_load_history("happy_path"))


@pytest.mark.asyncio
async def test_replay_risk_rejected() -> None:
    """Risk gate rejects the order → RISK_REJECTED terminal status."""
    replayer = Replayer(workflows=[OrderProcessingWorkflow])
    await replayer.replay_workflow(_load_history("risk_rejected"))


@pytest.mark.asyncio
async def test_replay_correction_timeout() -> None:
    """Validation fails; support team never corrects → CORRECTION_TIMEOUT."""
    replayer = Replayer(workflows=[OrderProcessingWorkflow])
    await replayer.replay_workflow(_load_history("correction_timeout"))


@pytest.mark.asyncio
async def test_replay_payment_expired() -> None:
    """Invalid RRN submitted; no resubmission in 7 days → PAYMENT_EXPIRED."""
    replayer = Replayer(workflows=[OrderProcessingWorkflow])
    await replayer.replay_workflow(_load_history("payment_expired"))


@pytest.mark.asyncio
async def test_replay_fulfillment_failed() -> None:
    """PIM activity raises non-retryable error → FULFILLMENT_FAILED, workflow FAILED."""
    replayer = Replayer(workflows=[OrderProcessingWorkflow])
    await replayer.replay_workflow(_load_history("fulfillment_failed"))
